spring:
  datasource:
    url: jdbc:mysql://101.132.151.45:3306/bws?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 101.132.151.45
    port: 6379
    redisson:
      config: |
        singleServerConfig:
          address: redis://101.132.151.45:6379          
          timeout: 3000
  application:
    name: BWS


rocketmq:
  name-server: 101.132.151.45:9876
  producer:
    group: BWS
    send-message-timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.project.model
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

server:
  port: 8080
