spring:
  datasource:
    url: jdbc:mysql://101.132.151.45:3306/bws?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 101.132.151.45
    port: 6379
  application:
    name: BWS

rocketmq:
  name-server: 101.132.151.45:9876
  producer:
    group: BWS
    send-message-timeout: 5000



server:
  port: 8081
